# Source: jxboot-helmfile-resources/templates/release-gpg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-release-gpg
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jenkins-release-gpg","properties":[{"name":"pubring.gpg","question":"The gpg public ring","defaultValue":"todo"}]}'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: azureKeyVault
  keyVaultName: potato
  data:
    - name: pubring.gpg
      key: jenkins-release-gpg
      property:
    - name: sec-jenkins.gpg
      key: jenkins-release-gpg
      property:
    - name: secring.gpg
      key: jenkins-release-gpg
      property:
    - name: trustdb.gpg
      key: jenkins-release-gpg
      property:
  template:
    type: Opaque
    metadata:
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"jenkins-release-gpg","properties":[{"name":"pubring.gpg","question":"The gpg public ring","defaultValue":"todo"}]}'
