apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      dns:
        resourceGroup: potato
        subscriptionId: potato
        tenantId: potato
      secretStorage:
        keyVaultName: potato
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: aks
    registry: happymudfish.azurecr.io
  environments:
  - key: dev
    owner: mellard-org
    repository: jx3v4
  ingress:
    domain: jx3v4.nelson.datacom.build
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: chris-mellard
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
