filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: nginx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
releases:
- chart: stable/nginx-ingress
  name: nginx-ingress
  version: 1.39.1
  values:
  - ../../versionStream/charts/stable/nginx-ingress/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}
