apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
    - name: external-dns
      mandatory: true
      properties:
        - name: azure.json
          key: externaldns
          question: enter a valid external-dns secret for the Azure DNS provider
          help: for secret details see https://github.com/kubernetes-sigs/external-dns#deploying-to-a-cluster
          template: |-
            {
            {{- if eq .Requirements.cluster.provider "aks" }}
              "resourceGroup": {{ .Requirements.cluster.azure.dns.resourceGroup }},
              "subscriptionId": {{ .Requirements.cluster.azure.dns.subscriptionId }},
              "tenantId": {{ .Requirements.cluster.azure.dns.tenantId }},
              "useManagedIdentityExtension": true
            {{- end }}
            }
