# Source: external-dns/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-3.2.0
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"external-dns","properties":[{"name":"azure.json","question":"enter a valid external-dns secret for the Azure DNS provider","help":"for secret details see https://github.com/kubernetes-sigs/external-dns#deploying-to-a-cluster","template":"{\n{{- if eq .Requirements.cluster.provider \"aks\" }}\n  \"resourceGroup\": {{ .Requirements.cluster.azure.dns.resourceGroup }},\n  \"subscriptionId\": {{ .Requirements.cluster.azure.dns.subscriptionId }},\n  \"tenantId\": {{ .Requirements.cluster.azure.dns.tenantId }},\n  \"useManagedIdentityExtension\": true\n{{- end }}\n}"}],"mandatory":true}'
spec:
  backendType: azureKeyVault
  keyVaultName: potato
  data:
    - name: azure.json
      key: externaldns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-3.2.0
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/managed-by: Helm
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"external-dns","properties":[{"name":"azure.json","question":"enter a valid external-dns secret for the Azure DNS provider","help":"for secret details see https://github.com/kubernetes-sigs/external-dns#deploying-to-a-cluster","template":"{\n{{- if eq .Requirements.cluster.provider \"aks\" }}\n  \"resourceGroup\": {{ .Requirements.cluster.azure.dns.resourceGroup }},\n  \"subscriptionId\": {{ .Requirements.cluster.azure.dns.subscriptionId }},\n  \"tenantId\": {{ .Requirements.cluster.azure.dns.tenantId }},\n  \"useManagedIdentityExtension\": true\n{{- end }}\n}"}],"mandatory":true}'
    type: Opaque
