# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-ddns-external-dns
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-3.2.0
    app.kubernetes.io/instance: external-ddns
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-ddns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-3.2.0
        app.kubernetes.io/instance: external-ddns
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/secret: a22c9571b533038d998a27f1d589d5157f75c8340b1c2698cdf61fbcc59b0509
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: external-ddns-external-dns
      containers:
        - name: external-dns
          image: "docker.io/bitnami/external-dns:0.7.2-debian-10-r6"
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --log-level=info
            - --log-format=text
            - --domain-filter=jx3v4.nelson.datacom.build
            - --policy=upsert-only
            - --provider=azure
            - --registry=txt
            - --interval=1m
            - --source=ingress
            # Azure Arguments
            - --azure-resource-group=secret
          env:
          ports:
            - name: http
              containerPort: 7979
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            # Azure mountPath(s)
            - name: azure-config-file
              mountPath: /etc/kubernetes/
              readOnly: true
      volumes:
        # Azure volume(s)
        - name: azure-config-file
          secret:
            secretName: external-ddns-external-dns
