filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.19
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-pipelines-visualizer
  version: 0.0.54
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-preview
  version: 0.0.133
  name: jx-preview
  values:
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jenkins-x/lighthouse
  version: 0.0.881
  name: lighthouse
  values:
  - ../../versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jenkins-x/nexus
  version: 0.1.35
  name: nexus
  values:
  - ../../versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: stable/chartmuseum
  version: 2.4.1
  name: chartmuseum
  values:
  - ../../versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-build-controller
  version: 0.0.15
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}
